from types import TracebackType
from typing import Any, Generic, Never, TypeVar, overload

T = TypeVar("T")
K = TypeVar("K")
INTERFACE_VERSION: int
__all__: list[str]

class AuthorizationError(PermissionError): ...

class Named(Generic[T]):
    def __init__(self, _unconstructible: Never) -> None: ...
    @property
    def value(self) -> T: ...
    def __repr__(self) -> str: ...

class Names:
    def __init__(self, _unconstructible: Never) -> None: ...
    def __enter__(self) -> tuple[Named[Any], ...]: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...

class Proof(Generic[K]):
    def __init__(self, _unconstructible: Never) -> None: ...
    @property
    def kind(self) -> str: ...
    @property
    def evidence(self) -> object: ...
    def __repr__(self) -> str: ...

class ProofKind(Generic[K]):
    def __init__(self, _unconstructible: Never) -> None: ...
    @property
    def kind(self) -> str: ...
    def require(self, proof: Proof[K], *about: Named[Any]) -> None: ...

class Prover(Generic[K]):
    def __init__(self, _unconstructible: Never) -> None: ...
    @property
    def kind(self) -> ProofKind[K]: ...
    def prove(self, *about: Named[Any], evidence: object = None) -> Proof[K]: ...

def name(value: T) -> Named[T]: ...
def names(*values: object) -> Names: ...
@overload
def define_proof(kind: str, *, tag: type[K]) -> Prover[K]: ...
@overload
def define_proof(kind: str) -> Prover[Any]: ...
